#!/usr/bin/env Rscript

args = commandArgs(trailingOnly=TRUE)

# author: [José Campos](https://jose.github.io/) (2024)

# load required library
library(data.table)
library(ggplot2)

# parse the input parameters
if (length(args) < 3) {
  stop("Three argument must be supplied: (i) raw data file, (ii) detailed_score.csv file generated by the statistical_analysis.R script, and (iii) output folder.", call.=FALSE)
}

embed_fonts_in_a_pdf <- function(pdf_path) {
  library('extrafont') # install.packages('extrafont')
  embed_fonts(pdf_path, options='-dSubsetFonts=true -dEmbedAllFonts=true -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dMaxSubsetPct=100')
}

# read raw data
rawdata <- read.table(args[1], sep=",", header=TRUE, stringsAsFactors=FALSE)
rawdata$timeBudget <- as.factor(rawdata$timeBudget)
rawdata$benchmark  <- as.factor(rawdata$benchmark)
rawdata$class      <- as.factor(rawdata$class)
rawdata$tool       <- as.factor(rawdata$tool)
rawdata$linesCoverageRatio      <- as.numeric(rawdata$linesCoverageRatio)
rawdata$conditionsCoverageRatio <- as.numeric(rawdata$conditionsCoverageRatio)
rawdata$mutantsKillRatio        <- as.numeric(rawdata$mutantsKillRatio)
rawdata$testcaseNumber          <- as.numeric(rawdata$testcaseNumber)
rawdata$uncompilableNumber      <- as.numeric(rawdata$uncompilableNumber)
rawdata$brokenTests             <- as.numeric(rawdata$brokenTests)
rawdata$failTests               <- as.numeric(rawdata$failTests)
rawdata$rmtest                  <- rawdata$brokenTests
rawdata$percrmtest              <- ifelse(rawdata$testcaseNumber == 0, 0, rawdata$rmtest / rawdata$testcaseNumber * 100)

# read pre-process raw data
scoresdata <- read.table(args[2], sep=",", header=TRUE, stringsAsFactors=FALSE)
scoresdata$timeBudget <- as.factor(scoresdata$timeBudget)
scoresdata$benchmark  <- as.factor(scoresdata$benchmark)
scoresdata$class      <- as.factor(scoresdata$class)
scoresdata$tool       <- as.factor(scoresdata$tool)
scoresdata$score      <- as.numeric(scoresdata$score)

output_dir <- args[3]
if (file.exists(output_dir) == FALSE)
  dir.create(output_dir, showWarnings = TRUE)

# Debug -----
agg <- aggregate(cbind(linesCoverageRatio, conditionsCoverageRatio, mutantsKillRatio) ~ timeBudget + tool + class, data=rawdata, FUN=mean)
agg <- aggregate(cbind(linesCoverageRatio, conditionsCoverageRatio, mutantsKillRatio) ~ timeBudget + tool, data=agg, FUN=mean)
print(agg)

# Classes with no coverage/mutation
x <- aggregate(cbind(linesCoverageRatio, conditionsCoverageRatio, mutantsKillRatio) ~ timeBudget + class, data=rawdata, FUN=max)
print(x)
cat('With 0 line coverage: \n')
print(x$'class'[x$'linesCoverageRatio' == 0.0])
cat('With 0 branch coverage: \n')
print(x$'class'[x$'conditionsCoverageRatio' == 0.0])
cat('With 0 mutation score: \n')
print(x$'class'[x$'mutantsKillRatio' == 0.0])
# -----

# Set output file to a PDF
output_file <- paste0(output_dir, '/boxplots.pdf')
# Create file
unlink(output_file)
pdf(file=output_file, family='Helvetica', width=7, height=7)

print_plot <- function(p) {
  p <- p + theme(legend.position='top',
    # legend.text = element_text(size=16),
    axis.text.x=element_text(size=16,  hjust=0.5, vjust=0.5),
    axis.text.y=element_text(size=16,  hjust=1.0, vjust=0.0),
    axis.title.x=element_text(size=18, hjust=0.5, vjust=0.0),
    axis.title.y=element_text(size=18, hjust=0.5, vjust=0.5)
  ) #+
  # geom_jitter(shape=16, position=position_jitter(0.2)) # 0.2 : degree of jitter in x direction
  print(p)
}

# Line coverage
x <- aggregate(linesCoverageRatio ~ timeBudget + tool + class, data=rawdata, FUN=mean)
p <- ggplot(x, aes(x=tool, y=linesCoverageRatio, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='% Line Coverage (higher is better)', fill='Time Budget (sec)')
print_plot(p)

# Branch coverage
x <- aggregate(conditionsCoverageRatio ~ timeBudget + tool + class, data=rawdata, FUN=mean)
p <- ggplot(x, aes(x=tool, y=conditionsCoverageRatio, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='% Branch Coverage (higher is better)', fill='Time Budget (sec)')
print_plot(p)

# Mutation score
x <- aggregate(mutantsKillRatio ~ timeBudget + tool + class, data=rawdata, FUN=mean)
p <- ggplot(x, aes(x=tool, y=mutantsKillRatio, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='% Mutation Score (higher is better)', fill='Time Budget (sec)')
print_plot(p)

# Gen tests
x <- aggregate(testcaseNumber ~ timeBudget + tool + class, data=rawdata, FUN=mean)
print(summary(x))
p <- ggplot(x, aes(x=tool, y=testcaseNumber, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='# Generated Tests', fill='Time Budget (sec)')
print_plot(p)

# Rm tests
x <- aggregate(percrmtest ~ timeBudget + tool + class, data=rawdata, FUN=mean)
print(summary(x))
p <- ggplot(x, aes(x=tool, y=percrmtest, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='% Broken and/or Flaky Tests (lower is better)', fill='Time Budget (sec)')
print_plot(p)

# Scores
average.scores <- aggregate(score ~ config + timeBudget + benchmark + class + tool, data=scoresdata, FUN=mean)
print(summary(average.scores))
p <- ggplot(average.scores, aes(x=tool, y=score, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='Score (higher is better)', fill='Time Budget (sec)')
print_plot(p)

# Ranking
ranks <- data.frame(matrix(ncol=4,nrow=0, dimnames=list(NULL, c("budget", "config", "tool", "rank"))))
for (conf in unique(average.scores$'config')) {
  # print(conf)

  for (timeBudget in unique(average.scores$'timeBudget')) {

    x <- average.scores[average.scores$'config' == conf & average.scores$'timeBudget' == timeBudget, ]
    x$'rank' <- rank(-x$"score", ties.method=c('min'))
    # print(x)

    x <- subset(x, select=c('timeBudget', 'config', 'tool', 'rank'))
    ranks <- rbind(ranks, x)
  }
}
print(head(ranks))
p <- ggplot(ranks, aes(x=tool, y=rank, fill=timeBudget)) +
  geom_boxplot() +
  labs(x='Tool', y='Rank (lower is better)', fill='Time Budget (sec)')
print_plot(p)

# Close output file
dev.off()
# Embed fonts
embed_fonts_in_a_pdf(output_file)

# EOF