#!/bin/bash

# Invoke maze's runtool, passing to it the following paramaters:
#  arg0 : search strategy or strategies (separated by comma, no space!)
#  arg1 : true/false whether or not suite minimalization is applied
#  arg2 : the --path-length-cov option of MAZE, e.g. 3. Use 0 to disable.
#  arg3 : the --target-path-aging option of MAZE

#java -cp lib/maze_runtool-1.1.jar sbst.runtool.Main PCS true 3 0

#java -cp lib/maze_runtool-1.1.jar sbst.runtool.Main SGS true 0 0

java -cp lib/maze_runtool-1.1.jar sbst.runtool.Main FOS,COS true 0 0
